[project]
name = "midi-ai-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "basic-pitch>=0.4.0",
    "fastapi[standard]>=0.115.13",
]
